---
ID: "dc0ba1d9-c569-42ad-ab44-fe211cab7ccb"
Parent: "583aec15-fe6c-44f4-a33f-da6bc637d5ca"
Template: "583aec15-fe6c-44f4-a33f-da6bc637d5ca"
Path: "/sitecore/client/Applications/FormsBuilder/Components/Layouts/Renderings/Composites/MCHContentManager/MCHContentManager-Parameters/__Standard Values"
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170217T102850Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
